### ISSUE TITLE
telnet session does not open

### ISSUE THREAD

**Issue by jidckii** [SmartFinn/unetlab-x-integration#1]
HI !
I'am using ubuntu 14.04.
Installing unetlab-x-integration_0.2.0_all.deb.
Click to R1 my unetlab, starts gnome-terminal, but telnet the session is not established.
I see clean window  gnome-terminal.
VNC worked.

**Comment by SmartFinn** [comment]
Hello!
I think that R1 just do not supported the console output.
Can you give me a link to an image, and I will test it.

**Comment by jidckii** [comment]
The problem is not specific R1.
Look: https://yadi.sk/i/JE2tTC-NuQ7Xe

**Comment by jidckii** [comment]
Solved a problem.
`echo "x-scheme-handler/telnet=unetlab-x-integration.desktop" >> usr/share/applications/defaults.list`

Pleace add feature, discover new connections in a new tab.
Thank You !

**Comment by SmartFinn** [comment]
Желательно было просто удалить строчку `x-scheme-handler/telnet` из `/usr/share/applications/defaults.list` и проверить следующей командой что все ок:

`xdg-mime query default x-scheme-handler/telnet` 

С табами в gnome-terminal боюсь не получится, т.к. он не умеет через cli открывать табы в уже созданных окнах, но может придумаю другое решением.

Спасибо.

**Comment by jidckii** [comment]
Думаю при установке следует чекать наличие ссылок на ярлыки и добавлять при отсутствии.
к примеру у меня нет их, и не заработало, пока руками не добавил:
```
$ xdg-mime query default x-scheme-handler/telnet
unetlab-x-integration.desktop
$ xdg-mime query default x-scheme-handler/ssh
$ xdg-mime query default x-scheme-handler/vnc
$ xdg-mime query default x-scheme-handler/docker
```

**Comment by SmartFinn** [comment]
Посмотрел как это устроено в других пакетах и полистав документацию пришел к выводу что ничего добавлять в `/usr/share/applications/defaults.list` не нужно, так как есть автоматически генерируемый файл `/usr/share/applications/mimeinfo.cache` в котором есть вся информация. В чем можно убедится выполнив:

```
gvfs-mime --query x-scheme-handler/telnet
gvfs-mime --query x-scheme-handler/capture
gvfs-mime --query x-scheme-handler/docker
```

Более того если воспользовавшись стандартным инструментарием и в процессе установки все же добавить дефолты, выполнив:

`xdg-mime default unetlab-x-integration.desktop x-scheme-handler/telnet`

то можно с удивлением обнаружить что изменился не `/usr/share/applications/defaults.list`,  а `~/.local/share/applications/mimeapps.list` и владельцем этого файла стал root из-за чего возникают уже другие проблемы.
