### ISSUE TITLE
Поддержка других дистрибутивов

### ISSUE THREAD

**Issue by tw4w3t** [SmartFinn/unetlab-x-integration#2]
Привет! 
Можете сделать подобное для Arch Linux?

**Comment by SmartFinn** [comment]
@tw4w3t,  приветствую!

Тестировал на Manjaro 15.09 XFCE и проблемы были в основном с именами бинарников и с ssh-askpass, обе решаемые. Решение первой добавил в инструкцию, а вторая требует единожды зайти по ssh на unetlab чтобы подтвердить отпечаток ключа:

`ssh root@<ip address unetlab>`

Кроме этого еще понадобилось добавить пользователя в группу wireshark и залогиниться чтобы заработал захват пакетов:

`sudo usermod -a -G wireshark $USER`

**Comment by SmartFinn** [comment]
@tw4w3t танцы с бубном уже не нужны, устанавливается все с помощью команды:

```
wget -qO- https://raw.github.com/SmartFinn/unetlab-x-integration/master/install.sh | sh
```

Пиши если возникнут проблемы.
