### ISSUE TITLE
No package x11-openssh-askpass available.

### ISSUE THREAD

**Issue by rainysexy** [SmartFinn/unetlab-x-integration#3]
Hello

I've been looking for unetlab intergration on linux for awhile and this look great

I'm using Korora 25, and when run the scrip i have this problem

[11:34 rainy ~/Downloads]$ wget -qO- https://raw.githubusercontent.com/SmartFinn/unetlab-x-integration/master/install.sh | sh
=> Detected distribution: korora 25 (fedora)
=> Install dependencies...
Last metadata expiration check: 2:15:27 ago on Tue Dec 13 09:19:29 2016.
Package telnet-1:0.17-65.fc24.x86_64 is already installed, skipping.
Package wireshark-qt-2.2.2-2.fc25.x86_64 is already installed, skipping.
No package x11-openssh-askpass available.
Error: Unable to find a match.

Could you help me with this? thank you

**Comment by SmartFinn** [comment]
Thanks for reporting. This should be fixed.
