### ISSUE TITLE
Choosing between wireshark QT vs GTK

### ISSUE THREAD

**Issue by rainysexy** [SmartFinn/unetlab-x-integration#4]
Hi!

First of all thank you for fixing the installer for the fedora, it works like a charm!

Now i only have a request that when the script run it use wireshark QT, but in my case i use GTK because it looks better that the QT version. ( i'm totally a newbie with linux)

So i want to know if there is a way to choose which wireshark version i want to run?
Thank you.

**Comment by SmartFinn** [comment]
Hi!

> We’re switching our user interface library from GTK+ to Qt.
> https://blog.wireshark.org/2013/10/switching-to-qt/

if you still want to use the GTK version you can do this with command:

```
sudo sed -i '/wireshark_cmd =/ s/wireshark -k/wireshark-gtk -k/' /usr/bin/unetlab-x-integration
```

But I don't recommend it.

**Comment by rainysexy** [comment]
Hi!

Thank you for your answer, after reading the article and your advice i decided to keep it with QT
Once again i want to thank you for this Unetlab-x intergration, i'm really appricated

P/S: the next version of the Unetlab is called "EVE-NG" , basically an Unetlab v2.0, i'm wondering if you will support the next version if there is any changes.
