### ISSUE TITLE
Connecting problem

### ISSUE THREAD

**Issue by UlasenkaUladzislau** [SmartFinn/unetlab-x-integration#5]
Здравствуйте, у меня была проблема как в таске https://github.com/SmartFinn/unetlab-x-integration/issues/1 .
Решил её при помощи команды (из Вашего последнего поста):

xdg-mime default unetlab-x-integration.desktop x-scheme-handler/telnet

После этого произошло открытие через терминал.

Версия ОС:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

Просто хотел поделиться решением проблемы. Спасибо за тулзу.

**Comment by SmartFinn** [comment]
Всегда пожалуйста!

Вообще для этой задачи уже есть цель в Makefile (`make defaults`)

```
defaults:
	xdg-mime default unetlab-x-integration.desktop x-scheme-handler/capture
	xdg-mime default unetlab-x-integration.desktop x-scheme-handler/telnet
	xdg-mime default unetlab-x-integration.desktop x-scheme-handler/docker
```
