### ISSUE TITLE
UNetLab-X-Integration open telnet sessions in one terminal window

### ISSUE THREAD

**Issue by mirisu2** [SmartFinn/unetlab-x-integration#6]
Hello, 
first of all, thank you for your UNetLab-X-Integration! 
By your installation guide and "Known issues" (3-4), it's work for Google Chrome on my Debian GNU/Linux 8 (3.16.0-4-amd64). But, one question. Is it possible to open all telnet sessions in one x-terminal? Not in many x-terminals.

**Comment by SmartFinn** [comment]
Yes, it is possible, but works with roxterm only (maybe somewhere else).

At first, update unetlab-x-integration to [latest version](https://github.com/SmartFinn/unetlab-x-integration/releases).

1. Copy `unetlab-x-integration.desktop` to home directory:

```
cp -f /usr/share/applications/unetlab-x-integration.desktop ~/.local/share/applications
```

2. Open it for editing:

```
gedit ~/.local/share/applications/unetlab-x-integration.desktop
```

3. Add `env OVERRIDE_TERMINAL_CMD="roxterm --tab -e" `  to Exec line to get the following code:

```
[Desktop Entry]
Name=UNetLab-X-Integration
Exec=env OVERRIDE_TERMINAL_CMD="roxterm --tab -e" unetlab-x-integration %u
TryExec=unetlab-x-integration
Type=Application
Categories=Network;
MimeType=x-scheme-handler/telnet;x-scheme-handler/capture;x-scheme-handler/docker;
X-KDE-Protocols=telnet,capture,docker
NoDisplay=true
```

CC @jidckii

**Comment by mirisu2** [comment]
Hello, thanks for reply!
1. I install roxterm.
2. Install latest version of unetlab-x-integration.
3. Copy and correct unetlab-x-integration.desktop file.
But, browser by clicking the devices, still open every session in separated **x-terminal**
What changes I need to do, to open the browser as expected?

**Comment by SmartFinn** [comment]
Does not work in Google Chrome only?

Try the command from [#does-not-work-in-google-chrome-but-works-in-another-browser](https://github.com/SmartFinn/unetlab-x-integration#does-not-work-in-google-chrome-but-works-in-another-browser)

**Comment by mirisu2** [comment]
Yes. Does not work in Google Chrome only. I  tried yet. But still in separated x-terminal, not in roxterm

**Comment by SmartFinn** [comment]
Did you get this window after click by nodes?

![screenshot from 2017-02-21 14-53-22](https://cloud.githubusercontent.com/assets/819186/23165599/a6a3dae6-f845-11e6-86ac-7e8367e93559.png)

**Comment by mirisu2** [comment]
Yes. When i click "Open...", open separated x-terminal console. I dont't know, why google chrome do not use roxterm

**Comment by SmartFinn** [comment]
Could you run command `xdg-open "telnet://route-server.he.net"` multiple times to test it what works fine?

**Comment by mirisu2** [comment]
Yes. It works fine. It's opens in separated x-terminal consoles.
route-server>

**Comment by mirisu2** [comment]
Sorry, When I run "xdg-open...", I see error:

> ** (x-terminal-emulator:5888): WARNING **: Binding '<Shift><Control>a' failed!
> Unable to bind hide_window key, another instance/window has it.
> <Window object at 0x7f68fa3399b0 (terminatorlib+window+Window at 0x280b040)> is not in registered window list

but, x-terminal console is opened and i see 

> route-server>

**Comment by SmartFinn** [comment]
It's should open telnet session in new roxterm tab.

Try the next:

```
sudo update-desktop-database -q

xdg-mime default unetlab-x-integration.desktop x-scheme-handler/capture
xdg-mime default unetlab-x-integration.desktop x-scheme-handler/telnet
xdg-mime default unetlab-x-integration.desktop x-scheme-handler/docker
```

and test it again.

**Comment by mirisu2** [comment]
As before, don't work as expected

**Comment by SmartFinn** [comment]
Please, run the next commands and paste result here

```
cat ~/.local/share/applications/mimeapps.list
cat ~/.local/share/applications/unetlab-x-integration.desktop
```

**Comment by mirisu2** [comment]
$ cat ~/.local/share/applications/mimeapps.list

> [Default Applications]
> image/gif=bl-image-viewer.desktop
> image/jpeg=bl-image-viewer.desktop
> image/png=bl-image-viewer.desktop
> image/svg+xml=bl-image-viewer.desktop
> text/plain=bl-text-editor.desktop
> text/html=bl-text-editor.desktop
> application/xml=bl-text-editor.desktop
> application/javascript=bl-text-editor.desktop
> x-directory/normal=bl-file-manager.desktop
> x-directory/gnome-default-handler=bl-file-manager.desktop
> inode/directory=bl-file-manager.desktop
> audio/mpeg=bl-mediaplayer.desktop
> audio/mp4=bl-mediaplayer.desktop
> audio/x-wav=bl-mediaplayer.desktop
> audio/aac=bl-mediaplayer.desktop
> video/webm=bl-mediaplayer.desktop
> video/x-ms-asf=bl-mediaplayer.desktop
> video/x-theora+ogg=bl-mediaplayer.desktop
> x-scheme-handler/capture=unetlab-x-integration.desktop
> x-scheme-handler/telnet=unetlab-x-integration.desktop
> x-scheme-handler/docker=unetlab-x-integration.desktop

$ cat ~/.local/share/applications/unetlab-x-integration.desktop

> [Desktop Entry]
> Name=UNetLab-X-Integration
> Exec= env OVERRIDE_TERMINAL_CMD="roxterm --tab -e" unetlab-x-integration %u
> TryExec=unetlab-x-integration
> Type=Application
> Categories=Network;
> MimeType=x-scheme-handler/telnet;x-scheme-handler/capture;x-scheme-handler/docker;
> X-KDE-Protocols=telnet,capture,docker
> NoDisplay=true

**Comment by SmartFinn** [comment]
Hmm, looks good.  I have no idea why it not working. Which desktop environment are you using?

**Comment by mirisu2** [comment]
Openbox

**Comment by SmartFinn** [comment]
Oh, I try to install Openbox on a virtual machine and test it there.

Please, test this command too:

```
env OVERRIDE_TERMINAL_CMD="roxterm --tab -e" unetlab-x-integration "telnet://route-server.he.net"
```

and try to delete space after `Exec=` in your `~/.local/share/applications/unetlab-x-integration.desktop`

**Comment by mirisu2** [comment]
> env OVERRIDE_TERMINAL_CMD="roxterm --tab -e" unetlab-x-integration "telnet://route-server.he.net"

opened in roxterm.

> and try to delete space after Exec=

not give effect

**Comment by SmartFinn** [comment]
Do you have same output?

![screenshot from 2017-02-21 20-25-32](https://cloud.githubusercontent.com/assets/819186/23179018/253ee4ac-f875-11e6-870e-fa03b58991d3.png)

**Comment by SmartFinn** [comment]
It is a bug in env (GNU coreutils) 8.23.

I found the workaround but it is ugly:

![screenshot from 2017-02-21 21-15-39](https://cloud.githubusercontent.com/assets/819186/23181289/17e3987c-f87d-11e6-8c94-b7bde94536d0.png)


Delete double quotes, and replace spaces between arguments to the special characters (Ctrl-V + Enter in vi/vim), or just replace unetlab-x-integration.desktop with [patched_unetlab-x-integration.desktop.zip](https://github.com/SmartFinn/unetlab-x-integration/files/791350/patched_unetlab-x-integration.desktop.zip)

**Comment by mirisu2** [comment]
Amazing! It's work fine in google chrome now! Thank you very march!

**Comment by DukeNuke3D** [comment]
> Yes, it is possible, but works with roxterm only (maybe somewhere else).
> 
> At first, update eve-ng-integration to [latest version](https://github.com/SmartFinn/eve-ng-integration/releases).
> 
> 1. Copy `eve-ng-integration.desktop` to home directory:
> 
> ```
> cp -f /usr/share/applications/eve-ng-integration.desktop ~/.local/share/applications
> ```
> 1. Open it for editing:
> 
> ```
> gedit ~/.local/share/applications/eve-ng-integration.desktop
> ```
> 1. Add `env OVERRIDE_TERMINAL_CMD="roxterm --tab -e" `  to Exec line to get the following code:
> 
> ```
> [Desktop Entry]
> Name=eve-ng-Integration
> Exec=env OVERRIDE_TERMINAL_CMD="roxterm --tab -e" eve-ng-integration %u
> TryExec=eve-ng-integration
> Type=Application
> Categories=Network;
> MimeType=x-scheme-handler/telnet;x-scheme-handler/capture;x-scheme-handler/docker;
> X-KDE-Protocols=telnet,capture,docker
> NoDisplay=true
> ```
> 1. Save it and try to open several nodes in your browser.
> 
> CC @jidckii

I succeeded in making it work under KDE 5.x Konsole. Need to edit /usr/bin/eve-ng-integration:
`    elif url.scheme == 'telnet':
        #cmd = 'telnet {host} {port}'.format(**data)
        cmd = 'konsole --new-tab -e telnet {host} {port}'.format(**data)

        term.execute(cmd)
`

**Comment by PercyDLR** [comment]
I don't know if anyone is still interested in this thread, but I found another solution. Editing the same file `/usr/bin/eve-ng-integration` mentioned by @DukeNuke3D, you can edit the function `_terminal_emulator_cmd` in line 31. You can look for your desktop enviroment, and you can modify the params used to execute the terminal emulator, or even change the used terminal emulator itself. For konsole, you could add here the `--new-tab` argument, separated by commas:
```
  def _terminal_emulator_cmd(self):
        [...]
        elif self._current_desktop('kde'):
            return ['konsole', '--new-tab', '-e']
        [...]
```
This method eliminated a bug I had when using @DukeNuke3D solution, where sometimes a telnet session would open in a separate terminal window, while others grouped together.
